### PR TITLE
issue 300 - added sourcemaps upload

### PR DESCRIPTION
**Pull request by Hardekerlis**

### CODE REVIEW

**Comment by Ole1288** [comment]
Needs better error messages for: when missing a .env files & when parsing of files fails.

**Comment by Ole1288** [comment]
Should have an option (or just by default) to support js files in the same dir if any sourcemaps also were found in it.

`file:///home/skycake/byteboost-cli/dist/commands/sourcemaps/upload.js:138
                        throw new Error(data.errors[0].message);
                              ^

Error: Invalid sourcemap file
    at UploadSoucemapsHandler.<anonymous> (file:///home/skycake/byteboost-cli/dist/commands/sourcemaps/upload.js:138:31)
    at Generator.next (<anonymous>)
    at fulfilled (file:///home/skycake/byteboost-cli/dist/commands/sourcemaps/upload.js:4:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0
`

**Comment by Hardekerlis** [comment]
> Needs better error messages for: when missing a .env files & when parsing of files fails.

How do I reproduce file parsing error @Ole1288 ?

**Comment by Ole1288** [comment]
> > Needs better error messages for: when missing a .env files & when parsing of files fails.
> 
> How do I reproduce file parsing error @Ole1288 ?

Build byteboost cli -> upload it's dist folder

**Comment by Ole1288** [comment]
Commands:
  upload [options] <path>  Upload sourcemaps to Byteboost
  help [command]           display help for command

what are the options?
how should the path be used? 
the help command should display this

**Comment by Ole1288** [comment]
Running this: ./.next --version 1

getting in the cli "0.0.1". 
did I upload anything? i dont know :(

**Comment by Ole1288** [comment]
have to run it like " ./.next --version=1" I dont know that as a user

**Comment by Ole1288** [comment]
I get this back

Couldn't find the .env file in path ./.next

      Env format:
      BYTEBOOST_TOKEN=<your-token>
      BYTEBOOST_DOMAIN=<your-domain>
      BYTEBOOST_ORGANIZATION=<your-organization>

do I really need .env i my soucemaps folder? Just take it from project root?

**Comment by Ole1288** [comment]
I added the .env file and I got:

Uploaded sourcemaps in 0.122 seconds

which is awesome, but should be prefixed with byteboost

**Comment by Hardekerlis** [comment]
> I get this back
> 
> Couldn't find the .env file in path ./.next
> 
> ```
>   Env format:
>   BYTEBOOST_TOKEN=<your-token>
>   BYTEBOOST_DOMAIN=<your-domain>
>   BYTEBOOST_ORGANIZATION=<your-organization>
> ```
> 
> do I really need .env i my soucemaps folder? Just take it from project root?

No you don't need your .env file in your .next folder. The path should be specified as root of your project and if you want to specifiy the build output dist you can specifiy it with --dist=".next"

**Comment by Hardekerlis** [comment]
> Commands: upload [options] Upload sourcemaps to Byteboost help [command] display help for command
> 
> what are the options? how should the path be used? the help command should display this

Can't fix this. byteboost-cli sourcemaps --help should behave like this. upload is a sub command of sourcemaps

**Comment by Hardekerlis** [comment]
> have to run it like " ./.next --version=1" I dont know that as a user

Need a new name for the param if this is a the case

**Pull request merged**
